#!/bin/bash

# Exit if we encounter a problem
set -e


# Define the root.
cd ${0%/*}/..
ROOT=$(pwd)
cd $ROOT

# Load the configuration file.
source $ROOT/config.sh

# Load the colors
source $ROOT/scripts/helper-colors.sh



# Composer executable.
[[ $COMPOSER && ${COMPOSER-x} ]] || COMPOSER=composer

# Build core and move the profile in place.
(
  # Save the sites/default directory if it exists.
  if [ -d web/sites/default ] || [ -L web/sites/default ]; then
    echo -e "${LBLUE}> Create backup of the web/sites/default directory${RESTORE}"
    chmod u+w web/sites/default
    mv web/sites/default sites-backup
    echo
  else
    mkdir -p web/sites/default
  fi
  chmod +w web/sites/* || true
  rm -Rf web || true

  # Build core.
  composer install

  # Restore the sites directory.
  if [ -d sites-backup ] || [ -L sites-backup ]; then
    echo -e "${LBLUE}> Restore backup of the web/sites/default directory${RESTORE}"
    rm -Rf web/sites/default
    mv sites-backup web/sites/default
    echo
  fi

)
